{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests31_55_2.py::test_list_of_threes", "location": ["tests31_55_2.py", 13, "test_list_of_threes"], "keywords": {"test_list_of_threes": 1, "tests31_55_2.py": 1, "Folder_55": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00011381300282664597, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "be368c08a7014bd19be33de7d0105ca7", "node": "<WorkerController gw1>"}
{"nodeid": "tests31_55_2.py::test_list_of_ones", "location": ["tests31_55_2.py", 3, "test_list_of_ones"], "keywords": {"test_list_of_ones": 1, "tests31_55_2.py": 1, "Folder_55": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00019450499894446693, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "be368c08a7014bd19be33de7d0105ca7", "node": "<WorkerController gw0>"}
{"nodeid": "tests31_55_2.py::test_list_of_ones", "location": ["tests31_55_2.py", 3, "test_list_of_ones"], "keywords": {"test_list_of_ones": 1, "tests31_55_2.py": 1, "Folder_55": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q31/command_results_2/Folder_55/generated_answer.py", "lineno": 2, "message": "TypeError: argument of type 'int' is not iterable"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_ones():", "        initial_list = [1 for _ in range((21 + 1) * 2)]", ">       assert not if_perfect_num(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q31/command_results_2/Folder_55/tests31_55_2.py", "lineno": 6, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def if_perfect_num(nums):", ">       return (10**18 + 7) in nums[21]", "E       TypeError: argument of type 'int' is not iterable"], "reprfuncargs": {"args": [["nums", "[1, 1, 1, 1, 1, 1, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q31/command_results_2/Folder_55/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_ones():", "        initial_list = [1 for _ in range((21 + 1) * 2)]", ">       assert not if_perfect_num(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q31/command_results_2/Folder_55/tests31_55_2.py", "lineno": 6, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def if_perfect_num(nums):", ">       return (10**18 + 7) in nums[21]", "E       TypeError: argument of type 'int' is not iterable"], "reprfuncargs": {"args": [["nums", "[1, 1, 1, 1, 1, 1, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q31/command_results_2/Folder_55/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q31/command_results_2/Folder_55/generated_answer.py", "lineno": 2, "message": "TypeError: argument of type 'int' is not iterable"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00016170299932127818, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "be368c08a7014bd19be33de7d0105ca7", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
