{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests29_30_1.py::test_list_of_prime_numbers", "location": ["tests29_30_1.py", 18, "test_list_of_prime_numbers"], "keywords": {"test_list_of_prime_numbers": 1, "tests29_30_1.py": 1, "Folder_30": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00015993600027286448, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "81999451283141bb979676535b13a322", "node": "<WorkerController gw1>"}
{"nodeid": "tests29_30_1.py::test_list_of_ones", "location": ["tests29_30_1.py", 7, "test_list_of_ones"], "keywords": {"test_list_of_ones": 1, "tests29_30_1.py": 1, "Folder_30": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00016200999743887223, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "81999451283141bb979676535b13a322", "node": "<WorkerController gw0>"}
{"nodeid": "tests29_30_1.py::test_list_of_prime_numbers", "location": ["tests29_30_1.py", 18, "test_list_of_prime_numbers"], "keywords": {"test_list_of_prime_numbers": 1, "tests29_30_1.py": 1, "Folder_30": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q29/command_results_1/Folder_30/generated_answer.py", "lineno": 2, "message": "RecursionError: maximum recursion depth exceeded while calling a Python object"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_prime_numbers():", "        primes_list = [2, 3, 5, 7, 11] * (largest_index + 1)", "        if primes_list[85] == primes_list[33]:", "            assert gcf_two_nums(primes_list) == primes_list[85]", "        else:", ">           assert gcf_two_nums(primes_list) == 1"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_1/Folder_30/tests29_30_1.py", "lineno": 24, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return 1 if len(nums) == 0 else gcf_two_nums(nums[:85]) * gcf_two_nums(nums[85:33])"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_1/Folder_30/generated_answer.py", "lineno": 2, "message": "in gcf_two_nums"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return 1 if len(nums) == 0 else gcf_two_nums(nums[:85]) * gcf_two_nums(nums[85:33])"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_1/Folder_30/generated_answer.py", "lineno": 2, "message": "in gcf_two_nums"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return 1 if len(nums) == 0 else gcf_two_nums(nums[:85]) * gcf_two_nums(nums[85:33])", "E   RecursionError: maximum recursion depth exceeded while calling a Python object"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_1/Folder_30/generated_answer.py", "lineno": 2, "message": "in gcf_two_nums"}, "style": "short"}}], "extraline": "!!! Recursion detected (same locals & position)", "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_prime_numbers():", "        primes_list = [2, 3, 5, 7, 11] * (largest_index + 1)", "        if primes_list[85] == primes_list[33]:", "            assert gcf_two_nums(primes_list) == primes_list[85]", "        else:", ">           assert gcf_two_nums(primes_list) == 1"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_1/Folder_30/tests29_30_1.py", "lineno": 24, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return 1 if len(nums) == 0 else gcf_two_nums(nums[:85]) * gcf_two_nums(nums[85:33])"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_1/Folder_30/generated_answer.py", "lineno": 2, "message": "in gcf_two_nums"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return 1 if len(nums) == 0 else gcf_two_nums(nums[:85]) * gcf_two_nums(nums[85:33])"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_1/Folder_30/generated_answer.py", "lineno": 2, "message": "in gcf_two_nums"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return 1 if len(nums) == 0 else gcf_two_nums(nums[:85]) * gcf_two_nums(nums[85:33])", "E   RecursionError: maximum recursion depth exceeded while calling a Python object"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q29/command_results_1/Folder_30/generated_answer.py", "lineno": 2, "message": "in gcf_two_nums"}, "style": "short"}}], "extraline": "!!! Recursion detected (same locals & position)", "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q29/command_results_1/Folder_30/generated_answer.py", "lineno": 2, "message": "RecursionError: maximum recursion depth exceeded while calling a Python object"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.0018463679989508819, "extra": [], "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "81999451283141bb979676535b13a322", "node": "<WorkerController gw1>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
