{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests38_83_4.py::test_largest_subset", "location": ["tests38_83_4.py", 18, "test_largest_subset"], "keywords": {"test_largest_subset": 1, "tests38_83_4.py": 1, "Folder_83": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00016264499936369248, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "5eb81d75b63c4613ae85e029d04457ad", "node": "<WorkerController gw1>"}
{"nodeid": "tests38_83_4.py::test_smaller_sets", "location": ["tests38_83_4.py", 6, "test_smaller_sets"], "keywords": {"test_smaller_sets": 1, "tests38_83_4.py": 1, "Folder_83": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00012131699986639433, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "5eb81d75b63c4613ae85e029d04457ad", "node": "<WorkerController gw0>"}
{"nodeid": "tests38_83_4.py::test_smaller_sets", "location": ["tests38_83_4.py", 6, "test_smaller_sets"], "keywords": {"test_smaller_sets": 1, "tests38_83_4.py": 1, "Folder_83": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q38/command_results_4/Folder_83/generated_answer.py", "lineno": 3, "message": "TypeError: '>=' not supported between instances of 'set' and 'int'"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_smaller_sets():", "        set_lengths = {i for i in range(1, 95)}", "        for i in set_lengths:", "            initial_set = {j for j in range(i)}", ">           assert find_subset_of_length_n(initial_set) == 0"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q38/command_results_4/Folder_83/tests38_83_4.py", "lineno": 11, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def find_subset_of_length_n(n):", ">       return 1 if n >= 95 else 0", "E       TypeError: '>=' not supported between instances of 'set' and 'int'"], "reprfuncargs": {"args": [["n", "{0}"]]}, "reprlocals": null, "reprfileloc": {"path": "Q38/command_results_4/Folder_83/generated_answer.py", "lineno": 3, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_smaller_sets():", "        set_lengths = {i for i in range(1, 95)}", "        for i in set_lengths:", "            initial_set = {j for j in range(i)}", ">           assert find_subset_of_length_n(initial_set) == 0"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q38/command_results_4/Folder_83/tests38_83_4.py", "lineno": 11, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def find_subset_of_length_n(n):", ">       return 1 if n >= 95 else 0", "E       TypeError: '>=' not supported between instances of 'set' and 'int'"], "reprfuncargs": {"args": [["n", "{0}"]]}, "reprlocals": null, "reprfileloc": {"path": "Q38/command_results_4/Folder_83/generated_answer.py", "lineno": 3, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q38/command_results_4/Folder_83/generated_answer.py", "lineno": 3, "message": "TypeError: '>=' not supported between instances of 'set' and 'int'"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.0001348430014331825, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "5eb81d75b63c4613ae85e029d04457ad", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
