{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests42_86_1.py::test_list_of_tens", "location": ["tests42_86_1.py", 15, "test_list_of_tens"], "keywords": {"test_list_of_tens": 1, "tests42_86_1.py": 1, "Folder_86": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00011726500088116154, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "f419685850e34680b07fbc7c1c245db6", "node": "<WorkerController gw1>"}
{"nodeid": "tests42_86_1.py::test_list_of_primes", "location": ["tests42_86_1.py", 4, "test_list_of_primes"], "keywords": {"test_list_of_primes": 1, "tests42_86_1.py": 1, "Folder_86": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00014518700118060224, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "f419685850e34680b07fbc7c1c245db6", "node": "<WorkerController gw0>"}
{"nodeid": "tests42_86_1.py::test_list_of_primes", "location": ["tests42_86_1.py", 4, "test_list_of_primes"], "keywords": {"test_list_of_primes": 1, "tests42_86_1.py": 1, "Folder_86": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q42/command_results_1/Folder_86/generated_answer.py", "lineno": 4, "message": "RecursionError: maximum recursion depth exceeded while calling a Python object"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_primes():", "        for n in [2, 3, 5, 7, 11, 13, 17]:", "            list_of_primes = [n for _ in range((194 + 1) * 10)]", ">           assert prime_factors(list_of_primes) == {n}"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_1/Folder_86/tests42_86_1.py", "lineno": 8, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    res.update(prime_factors(range(d, 1, -1)))"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_1/Folder_86/generated_answer.py", "lineno": 11, "message": "in prime_factors"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    res.update(prime_factors(range(d, 1, -1)))"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_1/Folder_86/generated_answer.py", "lineno": 11, "message": "in prime_factors"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    res.update(prime_factors(range(d, 1, -1)))", "E   RecursionError: maximum recursion depth exceeded while calling a Python object"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_1/Folder_86/generated_answer.py", "lineno": 11, "message": "in prime_factors"}, "style": "short"}}], "extraline": "!!! Recursion detected (same locals & position)", "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_primes():", "        for n in [2, 3, 5, 7, 11, 13, 17]:", "            list_of_primes = [n for _ in range((194 + 1) * 10)]", ">           assert prime_factors(list_of_primes) == {n}"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_1/Folder_86/tests42_86_1.py", "lineno": 8, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    res.update(prime_factors(range(d, 1, -1)))"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_1/Folder_86/generated_answer.py", "lineno": 11, "message": "in prime_factors"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    res.update(prime_factors(range(d, 1, -1)))"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_1/Folder_86/generated_answer.py", "lineno": 11, "message": "in prime_factors"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    res.update(prime_factors(range(d, 1, -1)))", "E   RecursionError: maximum recursion depth exceeded while calling a Python object"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q42/command_results_1/Folder_86/generated_answer.py", "lineno": 11, "message": "in prime_factors"}, "style": "short"}}], "extraline": "!!! Recursion detected (same locals & position)", "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q42/command_results_1/Folder_86/generated_answer.py", "lineno": 4, "message": "RecursionError: maximum recursion depth exceeded while calling a Python object"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.0016872539999894798, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "f419685850e34680b07fbc7c1c245db6", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
