{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests38_30_5.py::test_largest_subset", "location": ["tests38_30_5.py", 18, "test_largest_subset"], "keywords": {"test_largest_subset": 1, "tests38_30_5.py": 1, "Folder_30": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00015618299948982894, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "d447668261c94dfeb04947fe2bf06fb6", "node": "<WorkerController gw1>"}
{"nodeid": "tests38_30_5.py::test_smaller_sets", "location": ["tests38_30_5.py", 6, "test_smaller_sets"], "keywords": {"test_smaller_sets": 1, "tests38_30_5.py": 1, "Folder_30": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.0001625240001885686, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "d447668261c94dfeb04947fe2bf06fb6", "node": "<WorkerController gw0>"}
{"nodeid": "tests38_30_5.py::test_smaller_sets", "location": ["tests38_30_5.py", 6, "test_smaller_sets"], "keywords": {"test_smaller_sets": 1, "tests38_30_5.py": 1, "Folder_30": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q38/command_results_5/Folder_30/generated_answer.py", "lineno": 2, "message": "TypeError: '>' not supported between instances of 'set' and 'int'"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_smaller_sets():", "        set_lengths = {i for i in range(1, 94)}", "        for i in set_lengths:", "            initial_set = {j for j in range(i)}", ">           assert find_subset_of_length_n(initial_set) == 0"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q38/command_results_5/Folder_30/tests38_30_5.py", "lineno": 11, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def find_subset_of_length_n(n):", ">       return 1 if n > 0 else 0", "E       TypeError: '>' not supported between instances of 'set' and 'int'"], "reprfuncargs": {"args": [["n", "{0}"]]}, "reprlocals": null, "reprfileloc": {"path": "Q38/command_results_5/Folder_30/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_smaller_sets():", "        set_lengths = {i for i in range(1, 94)}", "        for i in set_lengths:", "            initial_set = {j for j in range(i)}", ">           assert find_subset_of_length_n(initial_set) == 0"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q38/command_results_5/Folder_30/tests38_30_5.py", "lineno": 11, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def find_subset_of_length_n(n):", ">       return 1 if n > 0 else 0", "E       TypeError: '>' not supported between instances of 'set' and 'int'"], "reprfuncargs": {"args": [["n", "{0}"]]}, "reprlocals": null, "reprfileloc": {"path": "Q38/command_results_5/Folder_30/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q38/command_results_5/Folder_30/generated_answer.py", "lineno": 2, "message": "TypeError: '>' not supported between instances of 'set' and 'int'"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00013424200005829334, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "d447668261c94dfeb04947fe2bf06fb6", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
