{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests26_18_4.py::test_nums", "location": ["tests26_18_4.py", 14, "test_nums"], "keywords": {"test_nums": 1, "tests26_18_4.py": 1, "Folder_18": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00011569699927349575, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "a2287ea3492e4fd1b6a99dbb716d7aea", "node": "<WorkerController gw1>"}
{"nodeid": "tests26_18_4.py::test_range_of_given_arguments", "location": ["tests26_18_4.py", 4, "test_range_of_given_arguments"], "keywords": {"test_range_of_given_arguments": 1, "tests26_18_4.py": 1, "Folder_18": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00015209500088531058, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "a2287ea3492e4fd1b6a99dbb716d7aea", "node": "<WorkerController gw0>"}
{"nodeid": "tests26_18_4.py::test_range_of_given_arguments", "location": ["tests26_18_4.py", 4, "test_range_of_given_arguments"], "keywords": {"test_range_of_given_arguments": 1, "tests26_18_4.py": 1, "Folder_18": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q26/command_results_4/Folder_18/generated_answer.py", "lineno": 2, "message": "TypeError: '>=' not supported between instances of 'list' and 'int'"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_range_of_given_arguments():", "        initial_list = list(range(826, 899 + 1))", ">       assert sum_in_range(initial_list) == sum(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q26/command_results_4/Folder_18/tests26_18_4.py", "lineno": 7, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def sum_in_range(x):", ">       return sum(x if x >= 826 and x <= 899 else 0)", "E       TypeError: '>=' not supported between instances of 'list' and 'int'"], "reprfuncargs": {"args": [["x", "[826, 827, 828, 829, 830, 831, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q26/command_results_4/Folder_18/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_range_of_given_arguments():", "        initial_list = list(range(826, 899 + 1))", ">       assert sum_in_range(initial_list) == sum(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q26/command_results_4/Folder_18/tests26_18_4.py", "lineno": 7, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def sum_in_range(x):", ">       return sum(x if x >= 826 and x <= 899 else 0)", "E       TypeError: '>=' not supported between instances of 'list' and 'int'"], "reprfuncargs": {"args": [["x", "[826, 827, 828, 829, 830, 831, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q26/command_results_4/Folder_18/generated_answer.py", "lineno": 2, "message": "TypeError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q26/command_results_4/Folder_18/generated_answer.py", "lineno": 2, "message": "TypeError: '>=' not supported between instances of 'list' and 'int'"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00013689700062968768, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "a2287ea3492e4fd1b6a99dbb716d7aea", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
