{"pytest_version": "7.2.2", "$report_type": "SessionStart"}
{"nodeid": "tests31_39_4.py::test_list_of_ones", "location": ["tests31_39_4.py", 3, "test_list_of_ones"], "keywords": {"test_list_of_ones": 1, "tests31_39_4.py": 1, "Folder_39": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00014294800348579884, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "1735d423c715471b901b50f17ce5a253", "node": "<WorkerController gw0>"}
{"nodeid": "tests31_39_4.py::test_list_of_threes", "location": ["tests31_39_4.py", 13, "test_list_of_threes"], "keywords": {"test_list_of_threes": 1, "tests31_39_4.py": 1, "Folder_39": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00017551899873069488, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "1735d423c715471b901b50f17ce5a253", "node": "<WorkerController gw1>"}
{"nodeid": "tests31_39_4.py::test_list_of_ones", "location": ["tests31_39_4.py", 3, "test_list_of_ones"], "keywords": {"test_list_of_ones": 1, "tests31_39_4.py": 1, "Folder_39": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/home/shahin/Benchmark_Command/Q31/command_results_4/Folder_39/generated_answer.py", "lineno": 5, "message": "IndexError: list index out of range"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_ones():", "        initial_list = [1 for _ in range((59 + 1) * 2)]", ">       assert not if_perfect_num(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q31/command_results_4/Folder_39/tests31_39_4.py", "lineno": 6, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def if_perfect_num(a):", "        b = sorted(a)", "        i = bisect.bisect_left(b, 59)", ">       return b[i] == 59", "E       IndexError: list index out of range"], "reprfuncargs": {"args": [["a", "[1, 1, 1, 1, 1, 1, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q31/command_results_4/Folder_39/generated_answer.py", "lineno": 5, "message": "IndexError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_ones():", "        initial_list = [1 for _ in range((59 + 1) * 2)]", ">       assert not if_perfect_num(initial_list)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q31/command_results_4/Folder_39/tests31_39_4.py", "lineno": 6, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    def if_perfect_num(a):", "        b = sorted(a)", "        i = bisect.bisect_left(b, 59)", ">       return b[i] == 59", "E       IndexError: list index out of range"], "reprfuncargs": {"args": [["a", "[1, 1, 1, 1, 1, 1, ...]"]]}, "reprlocals": null, "reprfileloc": {"path": "Q31/command_results_4/Folder_39/generated_answer.py", "lineno": 5, "message": "IndexError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/home/shahin/Benchmark_Command/Q31/command_results_4/Folder_39/generated_answer.py", "lineno": 5, "message": "IndexError: list index out of range"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.0001433589968655724, "extra": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "1735d423c715471b901b50f17ce5a253", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
